#!/bin/bash
set -eu -o pipefail

if [[ $(command -v podman) ]]; then
  podman container run \
    --name phpcs$$ \
    --rm \
    --security-opt label=disable \
    -v "$PWD":/work \
    shakiyam/phpcs "$@"
else
  docker container run \
    --name phpcs$$ \
    --rm \
    -u "$(id -u):$(id -g)" \
    -v "$PWD":/work:ro \
    shakiyam/phpcs "$@"
fi
